
steps:

# Build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/puppeteer:$REVISION_ID', '-f', 'Dockerfile', '.' ]

# Push
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/puppeteer:$REVISION_ID"]

# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials boxp-tk --zone asia-northeast1-a
    envsubst < k8s/deployment.yml > generated-deployment.yml
    kubectl apply -f generated-deployment.yml
