
steps:

# Build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/puppeteer:$REVISION_ID', '-f', 'Dockerfile', '.' ]

# Push
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/puppeteer:$REVISION_ID"]

# Apply environment variable
- name: 'loicmahieu/alpine-envsubst'
  args:
  - '-c'
  - |
    envsubst < k8s/deployment.yml > generated-deployment.yml

# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud config set container/use_client_certificate True
    gcloud container clusters get-credentials alice --zone asia-northeast1-a
    kubectl apply -f generated-deployment.yml
