apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: puppeteer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: puppeteer
    spec:
      containers:
      - name: puppeteer
        image: asia.gcr.io/boxp-tk/puppeteer:${CIRCLE_SHA1}
        env:
          - name: PUPPETEER_SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: slack-token
          - name: PUPPETEER_GITHUB_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: github-oauth-token
          - name: PUPPETEER_AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: aws-access-key
          - name: PUPPETEER_AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: aws-secret-key
          - name: PUPPETEER_DYNAMODB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: dynamodb-endpoint
          - name: PUPPETEER_PUBSUB_SUBSCRIPTION_NAME
            value: "puppeteer-cloud-builds"
          - name: PUPPETEER_K8S_DOMAIN
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: k8s-domain
          - name: PUPPETEER_K8S_INGRESS_NAME
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: k8s-ingress-name
          - name: PUPPETEER_DNS_ZONE
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: dns-zone
        resources:
          requests:
            cpu: 20m
