apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: puppeteer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: puppeteer
    spec:
      containers:
      - name: puppeteer
        image: asia.gcr.io/boxp-tk/puppeteer:${CIRCLE_SHA1}
        ports:
        - containerPort: 8080
        env:
          - name: PUPPETEER_WEBAPP_PORT
            value: "8080"
          - name: PUPPETEER_SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: slack-token
          - name: PUPPETEER_GITHUB_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: github-oauth-token
          - name: PUPPETEER_AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: aws-access-key
          - name: PUPPETEER_AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: aws-secret-key
          - name: PUPPETEER_DYNAMODB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: puppeteer
                key: dynamodb-endpoint
