apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: puppeteer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: puppeteer
    spec:
      containers:
      - name: puppeteer
        image: asia.gcr.io/boxp-tk/puppeteer:${CIRCLE_SHA1}
        ports:
        - containerPort: 8080
        env:
          - name: PUPPETEER_MY_WEBAPP_PORT
            value: 8080
          - name: PUPPETEER_EXAMPLE_PORT
            value: 8000
