apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sorcerer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sorcerer
    spec:
      containers:
      - name: sorcerer
        image: gcr.io/${PROJECT_ID}/sorcerer:${REVISION_ID}
        env:
          - name: SORCERER_SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: slack-token
          - name: SORCERER_GITHUB_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: github-oauth-token
          - name: SORCERER_AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: aws-access-key
          - name: SORCERER_AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: aws-secret-key
          - name: SORCERER_DYNAMODB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: dynamodb-endpoint
          - name: SORCERER_PUBSUB_SUBSCRIPTION_NAME
            value: "sorcerer-cloud-builds"
          - name: SORCERER_K8S_DOMAIN
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: k8s-domain
          - name: SORCERER_K8S_INGRESS_NAME
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: k8s-ingress-name
          - name: SORCERER_DNS_ZONE
            valueFrom:
              secretKeyRef:
                name: sorcerer
                key: dns-zone
        resources:
          requests:
            cpu: 20m
